version: '3.8'

services:
  db:
    image: postgres:15.4
    container_name: bd
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
